name = "orange-meets-public"

account_id = "8477399eb04accc1792af96aeaa25222"
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-10-07"
compatibility_flags = ["nodejs_compat"]

[site]
  bucket = "./public"

[[rules]]
type = "ESModule"
globs = ["**/@mediapipe/selfie_segmentation/**/*"]
fallthrough = true

[[rules]]
type = "ESModule"
globs = ["**/@tensorflow/**/*"]
fallthrough = true

[[rules]]
type = "ESModule"
globs = ["**/@tensorflow-models/**/*"]
fallthrough = true

[vars]
CALLS_APP_ID = "1ff13ac8f27014b77f7eb5bc178aceae"
TURN_SERVICE_ID = "46711d6c5759085dd70f599f6190ab94"
PUBLIC = "true"

[[durable_objects.bindings]]
name = "rooms"
class_name = "ChatRoom"

# Indicate that you want the ChatRoom and RateLimiter classes to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_sqlite_classes = ["ChatRoom", "RateLimiter"]

[[migrations]]
tag = "v2"
deleted_classes = ["RateLimiter"] 

# The necessary secrets are:
# - CALLS_APP_SECRET
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these


