name = "orange-meets"
compatibility_date = "2024-10-07"
main = "./build/index.js"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./public"

[vars]
CALLS_APP_ID = "760a3d269dd2ead6a4f0f4ae2ab9bfe5"

[[durable_objects.bindings]]
name = "rooms"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom"]


# The necessary secrets are:
# - CALLS_APP_SECRET
# To add secret, run `echo <VALUE> | wrangler secret put <NAME>`

# Optional secrets:
# OPENAI_API_TOKEN = ""
